language:
  haskell
ghc:
  - "7.4"
  - "7.10"
  - "8.4"
install:
  - cabal install --only-dependencies --enable-test --enable-benchmark
script:
  - cabal clean && cabal configure --enable-tests --enable-benchmark && cabal build && cabal test && cabal haddock
  