name: master

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master

jobs:
  stack-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: stack build
    - run: stack test

  cabal-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cabal update
    - run: cabal configure --enable-tests
    - run: cabal build
    - run: cabal test --test-show-details=always
    - run: cabal haddock
    - run: cabal check
    - run: cabal sdist

  metrics:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      LCOV_PATH: ./lcov.info
      # TODO: Remove this restriction once `stack test --coverage` is fixed in the next Stack release
      STACK_YAML: stack-8.6.5.yaml
    steps:
    - uses: actions/checkout@v2
    - name: Add $HOME/.local/bin to PATH
      run: echo "::add-path::$HOME/.local/bin"
    - name: Run tests with coverage
      run: stack test --coverage
    - name: Install hpc-lcov
      run: stack install hpc-lcov
    - name: Convert coverage results to LCOV format
      run: hpc-lcov -o ${{ env.LCOV_PATH }}
    - name: Upload coverage to Coverall 
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ env.LCOV_PATH }}
    - name: Run benchmarks
      run: stack bench

  hackage-upload:
    if: github.event_name == 'push' && startsWith(github.event.base_ref, 'refs/heads/master')
    needs:
      - stack-build
      - cabal-build
      - metrics
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload version to Hackage
      env:
        HACKAGE_USERNAME: ${{ secrets.HACKAGE_USERNAME }}
        HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}
      run: stack upload .
